CREATE TABLE IF NOT EXISTS books (
	book_id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	borrow_limit INTEGER NOT NULL DEFAULT 3,
	borrow_days INTEGER NOT NULL DEFAULT 14,
	fine_per_day NUMERIC(10, 2) NOT NULL DEFAULT 2.00
);

CREATE TABLE IF NOT EXISTS borrow_history (
	history_id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
	book_id INTEGER NOT NULL REFERENCES books(book_id) ON DELETE CASCADE,
	borrowed_on DATE NOT NULL,
	due_on DATE NOT NULL,
	returned_on DATE,
	fine NUMERIC(10, 2) NOT NULL DEFAULT 0.00
    statuss VARCHAR(20) DEFAULT 'BORROWED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
